version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - APP_DATABASE__PORT=5432
      - APP_DATABASE__HOST=db
      - APP_DATABASE__USER=postgres
      - APP_DATABASE__PASSWORD=postgres
      - APP_DATABASE__DATABASE_NAME=postgres
      - APP_DATABASE__REQUIRE_SSL=false
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
