application:
  host: 0.0.0.0
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "blogdb"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-authorization-token"
  timeout_milliseconds: 10000
passwordless:
  base_url: "https://v3.passwordless.dev"
  authorization_token: "jakepixl:public:9006360d3f1548e28de2bda4fde39456"
  authorization_secret: "jakepixl:secret:ec78c4c52ff34e72a098992027f673da"
  timeout_milliseconds: 10000