application:
  host: 0.0.0.0
  base_url: "https://jakepixl.dev"
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "admin@valink.io"
passwordless:
  base_url: "https://v3.passwordless.dev"